---
ls:
  .adoc: kebab-case | SCREAMING_SNAKE_CASE
  .puml: kebab-case

  .json: kebab-case
  .tf: kebab-case
  .yml: kebab-case
  .yaml: kebab-case

  .sh: kebab-case

  .css: kebab-case
  .html: kebab-case
  .js: kebab-case

  Dockerfile: PascalCase
  Vagrantfile: PascalCase
  Jenkinsfile: PascalCase

  .folderslint: lowercase
  .gitignore: lowercase
  .gitkeep: lowercase
  .yamllint: lowercase

ignore:
  - .ls-lint.yml
  - .idea
  - .git
  - node_modules
  - target
