---
name: CICD

on:
  push:
    branches-ignore:
      - dependabot/**
    tags:
      - v*
  pull_request:
    # branches: [ "main", "feat/*", "release/*" ]
    branches-ignore:
      - dependabot/**
  schedule:
    - cron: '0 2 * * 1' # https://crontab.guru

permissions:
  contents: read

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3

  lint-env-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run dotenvlinter in container
        run: docker run -i --rm --volume "$(pwd):/app" --workdir "/app" dotenvlinter/dotenv-linter:latest --exclude "*node_modules*" --recursive
        shell: bash

  lint-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run folderslint in container
        run: docker run -i --rm --volume "$(pwd):$(pwd)" --workdir "$(pwd)" sommerfeldio/folderslint:latest folderslint
        shell: bash

  lint-filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ls-lint in container
        run: docker run -i --rm --volume "$(pwd):/data" --workdir "/data" lslintorg/ls-lint:1.11.0
        shell: bash

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: node_modules target

  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: hadolint
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile

  check-links-in-adoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install asciidoc-link-check
        run: npm install --location=global asciidoc-link-check@1.0.15
        shell: bash
      - name: Validate links in all adoc files
        run: find . -name '*.adoc' -exec asciidoc-link-check -c .adoc-links.json -p {} \;
        shell: bash

  ci:
    runs-on: ubuntu-latest
    needs: ['lint-yaml', 'lint-env-files', 'lint-folders', 'lint-filenames', 'shellcheck', 'lint-dockerfile', 'check-links-in-adoc']
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build HTML
        run: |
          SRC_DIR="src/main"
          TARGET_DIR="target/content"

          docker run --rm --volume "$(pwd):/documents" asciidoctor/docker-asciidoctor:latest \
            asciidoctor-revealjs -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.9.2 "$SRC_DIR/index.adoc"

          rm -rf "$TARGET_DIR"
          mkdir -p "$TARGET_DIR"

          mv "$SRC_DIR/index.html" "$TARGET_DIR/index.html"
          cp -a "$SRC_DIR/images" "$TARGET_DIR"
        shell: bash
      - name: Set docker tag ('ci' for main or feature branch, 'release-candidate' for release branch)
        id: vars
        run: |
          echo ${{ github.ref }}

          TAG='ci'
          REF='refs/heads/release/'

          if [[ ${{ github.ref }} == *${REF}* ]]; then
            TAG='release-candidate'
          fi

          echo "tag = $TAG"
          echo "DOCKER_TAG=$TAG" >> $GITHUB_OUTPUT
        shell: bash
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker image build
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: sommerfeldio/website-tafelboy-de:${{ steps.vars.outputs.DOCKER_TAG }}

  cd-html-pages:
    runs-on: ubuntu-latest
    needs: ci
    if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/main'
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build HTML
        run: |
          SRC_DIR="src/main"
          TARGET_DIR="target/content"

          docker run --rm --volume "$(pwd):/documents" asciidoctor/docker-asciidoctor:latest \
            asciidoctor-revealjs -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.9.2 "$SRC_DIR/index.adoc"

          rm -rf "$TARGET_DIR"
          mkdir -p "$TARGET_DIR"

          mv "$SRC_DIR/index.html" "$TARGET_DIR/index.html"
          cp -a "$SRC_DIR/images" "$TARGET_DIR"
        shell: bash
      - name: Deploy (FTP)
        run: |
          FTP_HOST="w00f8074.kasserver.com"
          TARGET_DIR="target/content"

          echo "Change to directory containing the built Antora pages"
          cd "$TARGET_DIR" || exit
          ls -alF

          echo "Upload via FTP"
          docker run -i --rm \
            --volume "$(pwd):$(pwd)" \
            --workdir "$(pwd)" \
            sommerfeldio/ftp-client:latest ncftpput -R -v -u "${{ secrets.FTP_USER }}" -p "${{ secrets.FTP_PASS }}" "$FTP_HOST" / *
        shell: bash

  cd-docker-image:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    needs: ci
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get current tag name
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Re-Tag image sommerfeldio/website-tafelboy-de from :release-candidate to :${{ steps.vars.outputs.tag }} and :latest
        run: |
          VERSION_TAG="$(cut -d "v" -f2 <<< ${{ steps.vars.outputs.tag }})"
          docker pull sommerfeldio/website-tafelboy-de:release-candidate

          docker tag sommerfeldio/website-tafelboy-de:release-candidate sommerfeldio/website-tafelboy-de:latest
          docker tag sommerfeldio/website-tafelboy-de:release-candidate sommerfeldio/website-tafelboy-de:$VERSION_TAG

          docker push sommerfeldio/website-tafelboy-de:latest
          docker push sommerfeldio/website-tafelboy-de:$VERSION_TAG
      - name: Convert README from Asciidoc to Markdown for DockerHub description
        run: |
          sudo apt-get install -y pandoc asciidoc
          asciidoc -b docbook README.adoc
          pandoc -f docbook -t markdown_strict README.xml -o README.md
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: sommerfeldio/website-tafelboy-de
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md

  on-failure:
    runs-on: ubuntu-latest
    needs: ['ci', 'cd-html-pages', 'cd-docker-image', 'lint-yaml', 'lint-env-files', 'lint-folders', 'lint-filenames', 'shellcheck', 'lint-dockerfile', 'check-links-in-adoc']
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
