---
name: Organize Issues and Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/assets/organize/labels.yml
      - .github/workflows/organize.yml

permissions:
  contents: read
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/workflows/assets/organize/labels.yml
          skip-delete: false
          dry-run: false

  on-failure:
    runs-on: ubuntu-latest
    needs: ['labels']
    if: failure()

    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
